export const TUNING = {
  fixedStepSeconds: 1 / 20,
  ticksPerSecond: 20,
  roundSeconds: 45,
  roundTicks: 900,
  arenaWidth: 960,
  arenaHeight: 640,
  arenaPadding: 54,
  chickenRadius: 24,
  maxHealth: 12,
  baseSpeed: 41,
  movementDecisionTicks: 48,
  movementIntentTicks: 48,
  movementPairCooldownTicks: 48,
  movementActionLockTicks: 4,
  combatRange: 58,
  combatCooldownTicks: 16,
  combatActionLockTicks: 7,
  mutualAttackDamage: 3,
  blockedAttackDamage: 0.5,
  supportRange: 170,
  supportHealthThreshold: 9,
  supportCooldownTicks: 30,
  supportActionLockTicks: 9,
  supportShield: 3,
  shieldTicks: 52,
  knockdownTicks: 36,
  invulnerabilityTicks: 20,
  spotlightWindowTick: 480,
  spotlightDeadlineTick: 720,
  spotlightReservationLeadTicks: 64,
  maxHistory: 2_400,
} as const;

export type MatchSpeed = 1 | 2 | 4;
